routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\AnswerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/', [QuestionController::class, 'index']);
Route::resource('/questions', QuestionController::class);
Route::resource('/answers', AnswerController::class);

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'question_id', 
        'parent_id', 
        'description'
    ];

    public function question_rela(){
        return $this->belongsTo('App\Model\Question');
    }

    /**
     * The has Many Relationship
     *
     * @var array
     */
    public function replies()
    {
        //return $this->hasMany(Answer::class, 'parent_id');
        return $this->hasMany('App\Models\Answer', 'parent_id');
    }
}

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Answer;

class Question extends Model
{
    use HasFactory;
  
    protected $table = 'questions';
    public $timestamps = true;

    protected $fillable = [
        'description',
        'created_at'
    ];
   
    /**
     * The has Many Relationship
     *
     * @var array
     */
    
    public function answers_rela()
    {
        //return $this->hasMany(Answer::class)->whereNull('parent_id');
        return $this->hasMany(Answer::class);
    }
    
}

app/Models/Suggestion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Suggestion extends Model
{
    use HasFactory;
    public $table = "suggestion";

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'description'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use Illuminate\Http\Request;

class AnswerController extends Controller
{
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'description' => 'required|min:5'
        ], [
            'description.min' => "The answer must be at least 5 characters",
        ]);

        Answer::create($request->all());
   
        return redirect()->route('questions.index')
            ->with('success', 'Answer added successfully');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Question;
use App\Models\Answer;
use App\Models\Suggestion;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$questions = Question::withCount('answers_totals')->get();
        
        $questions = Question::withCount('answers_rela')
            ->orderBy('updated_at', 'desc')
            ->paginate(10);

        return view('questions.index', [
            'questions' => $questions
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $suggestion = Suggestion::inRandomOrder()->first();
        
        return view('questions.create',[
            'suggestion' => $suggestion
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'description' => ['regex:/^.*?\?$/', 'required', 'min:5'],
        ], [
            'description.regex' => "The question should ent with the character '?'",
            'description.required' => "This field is required",
            'description.min' => "The question must be at least 5 characters",
        ]);

        Question::create($request->all());

        return redirect()->route('questions.index')
            ->with('success', 'Question created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        $answers = Answer::query()
            ->where('question_id', $question->id)
            ->orderBy('id', 'asc')
            ->get();
        
        return view('questions.show', [
            'questions' => $question,
            'answers_list' => $answers
        ]);
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $question->delete();

        return redirect()->route('questions.index')
            ->with('success', 'Question deleted successfully');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>The Challenge - Vegan Activist</title>

    <!-- Bootstrap core CSS -->
    <link href="{{asset('vendor/bootstrap/css/bootstrap.css')}}" rel="stylesheet">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container">
        <a class="navbar-brand" href="/">Vegan Activist</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item active"></li>
            </ul>
        </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        @yield('content')
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="{{asset('vendor/jquery/jquery.slim.min.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  

</body>

</html>

resources/views/questions/answersDisplay.blade.php
@foreach($answers_show as $answer)
    <div class="display-answer" @if($answer->parent_id != null) style="margin-left:40px;" @endif>
        <p>{{ $answer->description }}</p>
        <a href="" id="reply"></a>
        <form action="{{ route('answers.store') }}" method="POST" >
            {{ csrf_field() }}
            <div class="form-group">
                <input type="text" name="description" class="form-control" />
                <input type="hidden" name="question_id" value="{{ $questions_id }}" />
                <input type="hidden" name="parent_id" value="{{ $answer->id }}" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-warning" value="Reply" />
            </div>
        </form>
    </div>
@endforeach

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="row mt-3 mb-3">
                <div class="col-sm-8 text-left font-italic">
                    <h2>Make a Question</h2>
                </div>
                <div class="col-sm-4 text-right">
                    <a class="btn btn-success" href="{{ route('questions.index') }}" title="Go back"> 
                        <i class="fas fa-backward "></i> 
                    </a>
                </div>
            </div>
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Requirement!</strong><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <form action="{{ route('questions.store') }}" method="POST" >
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <textarea type="text" 
                                name="description" 
                                class="form-control" 
                                placeholder="{{ $suggestion->description }}"></textarea>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Question</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('questions.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('questions.update', $question->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <textarea class="form-control" style="height:50px" name="description"
                        placeholder="Type a description">{{ $question->description }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-3 mb-3">
        <div class="col-sm-8 text-left font-italic">
            <h2>List of Questions</h2>
        </div>
        <div class="col-sm-4 text-right">
            <a class="btn btn-success" href="{{ route('questions.create') }}" title="Create a question"> 
                <i class="fas fa-plus-circle"></i>
            </a>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ $message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <table class="table table-bordered table-responsive-sm table-striped">
        <thead class="thead-dark">
            <th width="10%" class="text-center font-italic">#</th>
            <th width="50%" class="font-italic">Title</th>
            <th width="20%" class="text-center font-italic">Total Answers</th>
            <th width="20%" class="text-center font-italic">Action</th>
        </thead>
        <tbody>
        @foreach($questions as $question)
        <tr>
            <td class="text-center">{{ $loop->index + 1 }}</td>
            <td>{{ $question->description }}</td>
            <td class="text-center">
                <span class="badge badge-pill badge-info p-2">
                    {{ $question->answers_rela_count }}
                </span>
            </td>
            <td class="text-center">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{{ route('questions.show', $question->id) }}" title="show">
                        <button type="button" class="btn btn-success">Show</button>           
                    </a>
                    <form action="{{ route('questions.destroy', $question->id) }}" method="POST">
                        {{ csrf_field() }}
                        @method('DELETE')
                        <button type="submit" title="delete" class="btn btn-danger">
                            Delete
                        </button>
                    </form>
                </div>
            </td>
        </tr>
        @endforeach
        </tbody>

    </table>

    
    <nav class="pagination justify-content-center">
        {{ $questions->links("pagination::bootstrap-4") }}    
    </nav>
    

@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header col-sm-12">
                    <div class="row mt-3 mb-3">
                        <div class="col-sm-8 text-left font-italic">
                            <h2>{{ $questions->description }}</h2>
                        </div>
                        <div class="col-sm-4 text-right">
                            <a class="btn btn-primary" href="{{ route('questions.index') }}" title="Go back"> 
                                <i class="fas fa-backward "></i> 
                            </a>
                        </div>
                    </div>
                </div>
                @if ($errors->any())
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Requirement!</strong><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                @include(
                        'questions.answersDisplay', 
                        [
                            'answers_show' => $answers_list, 
                            'questions_id' => $questions->id
                        ]
                    )
                <div class="card-body">
                    <h4 class="font-italic">Add Answer</h4>
                    <form action="{{ route('answers.store') }}" method="POST" >
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <textarea class="form-control" 
                                        name="description" 
                                        class="form-control"></textarea>
                                    <input type="hidden" name="question_id" value="{{ $questions->id }}" />
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection